http:
  port: ${PORT}
admin:
  port: 9876
  host: ${HOST}
apiEndpoints:
  api:
    host: ${HOST}
    paths: '/ip'
  postUsers:
    host: ${HOST}
    paths: '/user/create'
  getCommendsProperty:
    host: ${HOST}
    paths: '/commends-property/:id'
  postCreateCommendPerson:
    host: ${HOST}
    paths: '/commend-person/create'
  postCreateCommendProperty:
    host: ${HOST}
    paths: '/commend-property/create'
  postLogin:
    host: ${HOST}
    paths: '/user/login'
  getUser:
    host: ${HOST}
    paths: '/user/:id'
  getCommendProperty:
    host: ${HOST}
    paths: '/commend-property/:id'
  getReservesPerson:
    host: ${HOST}
    paths: '/reserve/person-id/:id'
  createReserve:
    host: ${HOST}
    paths: '/reserve/create'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - body-parser
  - create-user
  - commeds-property
  - create-commend-person
  - create-commend-property
  - login
  - get-user
  - get-commend-property
  - get-reserves
  - create-reserve
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  postUserPipeline:
    apiEndpoints:
      - postUsers
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-user:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']
  
  getCommendsPropertyPipeline:
    apiEndpoints:
      - getCommendsProperty
    policies:
      - commeds-property:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}', '${URL_MICROSERVICE_PROPERTIES}']

  postCreateCommendsPersonPipeline:
    apiEndpoints:
      - postCreateCommendPerson
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-commend-person:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']

  postCreateCommendsPropertyPipeline:
    apiEndpoints:
      - postCreateCommendProperty
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-commend-property:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']
              
  postLoginPipeline:
    apiEndpoints:
      - postLogin
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - login:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']

  getUserPipeline:
    apiEndpoints:
      - getUser
    policies:
      - get-user:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']

  getCommendPropertyPipeline:
    apiEndpoints:
      - getCommendProperty
    policies:
      - get-commend-property:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']

  getReservesPersonPipeline:
    apiEndpoints:
      - getReservesPerson
    policies:
      - get-reserves:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICES_RESERVES}']

  postCreateReservePipeline:
    apiEndpoints:
      - createReserve
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-reserve:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICES_RESERVES}']