http:
  port: ${PORT}
admin:
  port: 9876
  host: ${HOST}
apiEndpoints:
  api:
    host: ${HOST}
    paths: '/ip'
  postUsers:
    host: ${HOST}
    paths: '/user/create'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - body-parser
  - create-user
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  postUserPipeline:
    apiEndpoints:
      - postUsers
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-user:
          - action:
              changeOrigin: true
              baseUrl: ['${URL_MICROSERVICE_COMMENDS}']
