# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
   express-gateway-plugin-body-parser: {}
   createUserPolicy:
     package: './plugins/create-user.manifest.js'
   commendsProperty:
     package: './aggregators/plugins/commends-property.js'
   createCommendPersonPolicy:
     package: './plugins/create-commend-person.manifest.js'
   createCommendPropertyPolicy:
     package: './plugins/create-commend-property.manifest.js'
   loginPolicy:
     package: './plugins/login.manifest.js'
   getUserPolicy:
     package: './plugins/get-user.manifest.js'
   getCommendsPropertyPolicy:
     package: './plugins/get-commend-property.manifest.js'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
